# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: postgresql
  database: postgresql_development
  username: karunakar 
  password:  

test:
  adapter: postgresql
  database: postgresql_test
  username: karunakar 
  password:  

production:
  adapter: postgresql
  database: postgresql_production
  username: karunakar 
  password:  

